
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

/*
 * SAP-3 Processor Top-Level Module
 *
 * This is the main module for the SAP-3 8-bit processor implementation.
 * It integrates all processor components: controller, ALU, registers,
 * memory, and I/O interfaces. The processor executes instructions
 * from memory and controls external displays and LEDs.
 *
 * The module uses a shared 16-bit bus for data transfer between components,
 * with tri-state drivers controlling which component drives the bus.
 */

module Computer1CB121_Top(

	//////////// CLOCK //////////
	input 		          		CLOCK_21,    // 21.4772MHz system clock
	input 		          		RESET_N,     // Active-low reset

	//////////// PS/2 //////////
	input 		          		PS2_CLK,     // PS/2 Keyboard Clock
	input 		          		PS2_DAT,     // PS/2 Keyboard Data

	//////////// UART //////////
	output		          		UART_TXD,    // UART Transmit Data
	input 		          		UART_RXD,    // UART Receive Data

	//////////// VGA //////////
	output		          		VGA_HSYNC,
	output		          		VGA_VSYNC,
	output		     [5:0]		VGA_R,
	output		     [5:0]		VGA_G,
	output		     [5:0]		VGA_B,

	//////////// LED //////////
	output		     [7:0]		LEDR         // LED outputs
	
);

// Internal control signals
wire step_mode = 1'b0; // Disabled for now, will map to keyboard later

// 25.175 MHz clock for VGA and system
wire clk_25m;

// Internal 16-bit data bus
reg[15:0] bus;

// Output port state and address latch
reg [71:0] port_out;
reg [7:0] oar_addr;

// Reset and clock signals
wire rst;
wire hlt;
wire clk;
wire hlt_m;
wire step_clk_pulse;

// Register file interface signals
wire[4:0] reg_rd_sel;
wire[4:0] reg_wr_sel;
wire[1:0] reg_ext;
wire reg_oe;
wire reg_we;
wire[15:0] reg_out;

// Memory interface signals
wire mem_mar_we;
wire mem_ram_we;
wire mem_oe;
wire[7:0] mem_out;

// VGA memory interface signals (to be connected to VGA controller later)
wire [12:0] vga_gfx_addr;
wire [7:0]  vga_gfx_data;
wire [11:0] vga_txt_addr;
wire [7:0]  vga_txt_data;
wire [10:0] vga_font_addr;
wire [7:0]  vga_font_data;
wire [7:0]  ink_color;
wire [7:0]  bg_color;

// Instruction register interface signals
wire ir_we;
wire[7:0] ir_out;

// ALU interface signals
wire alu_cs;
wire alu_flags_we;
wire alu_a_we;
wire alu_a_store;
wire alu_a_restore;
wire alu_tmp_we;
wire alu_oe;
wire alu_flags_oe;
wire[4:0] alu_op;
wire[7:0] alu_flags;
wire[7:0] alu_out;

// Output port signals
wire oar_we;
wire out_we;

// PS/2 keyboard signals
wire [7:0] ps2_scan_code;
wire ps2_scan_code_ready;

// UART signals
wire [7:0] uart_rx_data;
wire uart_rx_done;
wire uart_tx_busy;

// Signal assignments
assign rst = ~RESET_N;           // Convert active-low to active-high reset

assign LEDR = port_out[7:0];     // Connect LEDs to output port

// Bus multiplexing logic: only one component drives the bus at a time
always @(*) begin
	bus = 16'b0;

	if (reg_oe)
		bus = reg_out;           // Register file drives bus
	else if (mem_oe)
		bus = {8'b0, mem_out};   // Memory drives bus
	else if (alu_oe)
		bus = {8'b0, alu_out};   // ALU drives bus
	else if (alu_flags_oe)
		bus = {8'b0, alu_flags}; // ALU flags drive bus
end

// Output port latch for I/O operations
always @(posedge clk or posedge rst) begin
    if (rst) begin
        oar_addr <= 8'b0;
        port_out <= 72'b0;
    end else begin
        if (oar_we)
            oar_addr <= bus[7:0];

        if (out_we) begin
            case (oar_addr)
                8'd0: port_out[7:0] <= bus[7:0];
                8'd1: port_out[35:0] <= {28'b0, bus[7:0]};
                8'd2: port_out[71:36] <= {28'b0, bus[7:0]};
                default: ;
            endcase
        end
    end
end

// PLL to generate 25.175 MHz from 21.4772 MHz input
pll sys_pll(
	.areset(1'b0), // Do not reset the PLL with the user button to avoid clock instability
	.inclk0(CLOCK_21),
	.c0(clk_25m)
);

// Step button controller for manual clock stepping
step_button step_button(
	.clk(clk_25m),
	.rst(rst),
	.step_mode(step_mode),
	.step_clk_pulse(step_clk_pulse),
	.hlt_m(hlt_m)
);

// Clock generator with halt and step controls
clock clock(
	.hlt(hlt | hlt_m),
	.step_pulse(step_clk_pulse),
	.clk_in(clk_25m),
	.clk_out(clk)
);

// Register file: contains all CPU registers (BC, DE, HL, WZ, PC, SP)
reg_file reg_file(
	.clk(clk),
	.rst(rst),
	.rd_sel(reg_rd_sel),
	.wr_sel(reg_wr_sel),
	.ext(reg_ext),
	.we(reg_we),
	.data_in(bus),
	.data_out(reg_out)
);

// Memory subsystem: RAM and Memory Address Register
memory memory(
	.clk(clk),
	.rst(rst),
	.mar_we(mem_mar_we),
	.ram_we(mem_ram_we),
	.bus(bus),
	.out(mem_out),
	.vga_gfx_addr(vga_gfx_addr),
	.vga_gfx_data(vga_gfx_data),
	.vga_txt_addr(vga_txt_addr),
	.vga_txt_data(vga_txt_data),
	.vga_font_addr(vga_font_addr),
	.vga_font_data(vga_font_data),
	.ink_color(ink_color),
	.bg_color(bg_color)
);

// Instruction Register: holds current instruction opcode
ir ir(
	.clk(clk),
	.rst(rst),
	.we(ir_we),
	.bus(bus[7:0]),
	.out(ir_out)
);

alu alu(
	.clk(clk),
	.rst(rst),
	.cs(alu_cs),
	.flags_we(alu_flags_we),
	.a_we(alu_a_we),
	.a_store(alu_a_store),
	.a_restore(alu_a_restore),
	.tmp_we(alu_tmp_we),
	.op(alu_op),
	.bus(bus[7:0]),
	.flags(alu_flags),
	.out(alu_out)
);

// Controller: generates control signals based on instruction opcode
controller controller(
	.clk(clk),
	.rst(rst),
	.opcode(ir_out),
	.flags(alu_flags),
	.out({
		oar_we,
		out_we,
		hlt,
		alu_cs,
		alu_flags_we,
		alu_a_we,
		alu_a_store,
		alu_a_restore,
		alu_tmp_we,
		alu_op,
		alu_oe,
		alu_flags_oe,
		reg_rd_sel,
		reg_wr_sel,
		reg_ext,
		reg_oe,
		reg_we,
		mem_ram_we,
		mem_mar_we,
		mem_oe,
		ir_we
		})
);

// PS/2 Keyboard Interface
ps2_keyboard ps2_keyboard_inst(
	.clk(clk_25m),
	.rst(rst),
	.ps2_clk(PS2_CLK),
	.ps2_dat(PS2_DAT),
	.scan_code(ps2_scan_code),
	.scan_code_ready(ps2_scan_code_ready)
);

// UART Interface (Hardware loop from PS/2 to UART TX)
uart #(
	.CLOCKS_PER_BIT(219) // 25.175MHz / 115200 baud
) uart_inst (
	.clk(clk_25m),
	.rst(rst),
	.rx(UART_RXD),
	.tx(UART_TXD),
	.tx_data(ps2_scan_code),         // Transmit the keyboard scan code directly
	.tx_we(ps2_scan_code_ready),     // Trigger transmission when a new byte is ready
	.tx_busy(uart_tx_busy),
	.rx_data(uart_rx_data),
	.rx_done(uart_rx_done)
);

// VGA Display Controller
display_controller vga_ctrl(
	.clk(clk_25m),
	.rst(rst),
	.vga_gfx_addr(vga_gfx_addr),
	.vga_gfx_data(vga_gfx_data),
	.vga_txt_addr(vga_txt_addr),
	.vga_txt_data(vga_txt_data),
	.vga_font_addr(vga_font_addr),
	.vga_font_data(vga_font_data),
	.layer_enable(2'b11), // Both layers enabled by default
	.ink_color(ink_color),
	.bg_color(bg_color),
	.vga_hsync(VGA_HSYNC),
	.vga_vsync(VGA_VSYNC),
	.vga_r(VGA_R),
	.vga_g(VGA_G),
	.vga_b(VGA_B)
);

endmodule
