
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

/*
 * SAP-3 Processor Top-Level Module
 *
 * This is the main module for the SAP-3 8-bit processor implementation.
 * It integrates all processor components: controller, ALU, registers,
 * memory, and I/O interfaces. The processor executes instructions
 * from memory and controls external displays and LEDs.
 *
 * The module uses a shared 16-bit bus for data transfer between components,
 * with tri-state drivers controlling which component drives the bus.
 */

module Computer1CB121_Top(

	//////////// CLOCK //////////
	input 		          		CLOCK_21,    // 21.4772MHz system clock
	input 		          		RESET_N,     // Active-low reset

	//////////// PS/2 //////////
	input 		          		PS2_CLK,     // PS/2 Keyboard Clock
	input 		          		PS2_DAT,     // PS/2 Keyboard Data

	//////////// DB9 / UART Ports //////////
	input 		          		UART_RXD,    // DB9 1# Pin 2
	output		          		UART_TXD,    // DB9 1# Pin 3

	//////////// USB //////////
	inout 		          		USBP2,       // FPGA Pin 239
	inout 		          		USBN2,       // FPGA Pin 238

	//////////// VGA //////////
	output		          		VGA_HSYNC,
	output		          		VGA_VSYNC,
	output		     [5:0]		VGA_R,
	output		     [5:0]		VGA_G,
	output		     [5:0]		VGA_B,

	//////////// LED //////////
	output		     [7:0]		LEDR,        // LED outputs

	//////////// AUDIO //////////
	output		     [5:0]		AUDIO_L,     // 6-bit PCM Left Channel
	output		     [5:0]		AUDIO_R,     // 6-bit PCM Right Channel
	
	//////////// SD Card //////////
	output 		          		SD_CLK,      // SPI Clock
	output 		          		SD_CMD,      // SPI MOSI
	input  		          		SD_DAT0,     // SPI MISO
	output 		          		SD_DAT1,     // Unused in SPI, must be pulled high
	output 		          		SD_DAT2,     // Unused in SPI, must be pulled high
	output 		          		SD_DAT3      // SPI CS
	
);

// Internal control signals
wire step_mode = 1'b0; // Disabled for now, will map to keyboard later

wire clk_21mhz;
// PLL generated 21.4772 MHz clock for system and VGA (Phase-Aligned)
wire clk_sys = clk_21mhz;

// Internal 16-bit data bus
reg[15:0] bus;

// Output port state and address latch
reg [71:0] port_out;
reg [7:0] oar_addr;

// Reset and clock signals
wire rst;
wire hlt;
wire clk;
wire hlt_m;
wire step_clk_pulse;

// Register file interface signals
wire[4:0] reg_rd_sel;
wire[4:0] reg_wr_sel;
wire[1:0] reg_ext;
wire reg_oe;
wire reg_we;
wire[15:0] reg_out;

// Memory interface signals
wire mem_mar_we;
wire mem_ram_we;
wire mem_oe;
wire[7:0] mem_out;

// VGA memory interface signals (to be connected to VGA controller later)
wire [13:0] vga_gfx_addr;
wire [7:0]  vga_gfx_data;
wire [11:0] vga_txt_addr;
wire [7:0]  vga_txt_data;
wire [10:0] vga_font_addr;
wire [7:0]  vga_font_data;
wire [7:0]  ink_color;
wire [7:0]  bg_color;
wire [6:0]  cursor_x;
wire [4:0]  cursor_y;
wire [1:0]  cursor_style;
wire [7:0]  gfx_ink_color;
wire        vga_vblank;

// Instruction register interface signals
wire ir_we;
wire[7:0] ir_out;

// ALU interface signals
wire alu_cs;
wire alu_flags_we;
wire alu_a_we;
wire alu_a_store;
wire alu_a_restore;
wire alu_tmp_we;
wire alu_oe;
wire alu_flags_oe;
wire[4:0] alu_op;
wire[7:0] alu_flags;
wire[7:0] alu_out;

// Output port signals
wire oar_we;
wire out_we;
wire in_oe;

// PS/2 keyboard signals
wire [7:0] ps2_scan_code;
wire ps2_scan_code_ready;

// UART signals
wire [7:0] uart_rx_data;
wire uart_rx_done;
wire uart_tx_busy;

// SD Card SPI signals
wire [7:0] sd_rx_data;
wire sd_spi_ready;
reg sd_cs_n;
reg sd_fast_mode;
reg sd_tx_start;
reg [7:0] sd_tx_latch;
reg out_we_m1;
reg out_we_m2;
reg out_we_m3;

// SD Card Activity LEDs
reg [19:0] sd_rd_timer;
reg [19:0] sd_wr_timer;

always @(posedge clk_sys or posedge rst) begin
    if (rst) begin
        sd_rd_timer <= 20'd0;
        sd_wr_timer <= 20'd0;
    end else begin
        if (in_oe && (oar_addr == 8'h0A))
            sd_rd_timer <= 20'd1000000; // ~46ms at 21.47MHz
        else if (sd_rd_timer > 0)
            sd_rd_timer <= sd_rd_timer - 1'b1;

        if (out_we && (oar_addr == 8'h0A))
            sd_wr_timer <= 20'd1000000;
        else if (sd_wr_timer > 0)
            sd_wr_timer <= sd_wr_timer - 1'b1;
    end
end

// Signal assignments
wire kb_sys_reset;
assign rst = (~RESET_N) | kb_sys_reset; // Combine physical and keyboard soft-reset

assign LEDR = {(sd_rd_timer > 0), (sd_wr_timer > 0), port_out[5:0]}; // Connect LEDs to output port

// PS/2 Keyboard Latch
reg [7:0] kb_data;
reg       kb_ready;

always @(posedge clk_sys or posedge rst) begin
    if (rst) begin
        kb_data <= 8'b0;
        kb_ready <= 1'b0;
    end else begin
        if (ps2_scan_code_ready) begin
            kb_data <= ps2_scan_code;
            kb_ready <= 1'b1;
        end else if (in_oe && oar_addr == 8'h00) begin
            kb_ready <= 1'b0;
        end
    end
end

// SD Card SPI Start Pulse Generator (clk_sys domain)
wire out_we_rising = out_we_m2 && !out_we_m3;

always @(posedge clk_sys or posedge rst) begin
    if (rst) begin
        sd_tx_start <= 1'b0;
        out_we_m1 <= 1'b0;
        out_we_m2 <= 1'b0;
        out_we_m3 <= 1'b0;
    end else begin
        out_we_m1 <= out_we;
        out_we_m2 <= out_we_m1;
        out_we_m3 <= out_we_m2;
        
        if (out_we_rising && (oar_addr == 8'h0A)) begin
            sd_tx_start <= 1'b1;
        end else begin
            sd_tx_start <= 1'b0;
        end
    end
end

// UART RX Latch
reg [7:0] uart_data_in;
reg       uart_ready;

always @(posedge clk_sys or posedge rst) begin
    if (rst) begin
        uart_data_in <= 8'b0;
        uart_ready <= 1'b0;
    end else begin
        if (uart_rx_done) begin
            uart_data_in <= uart_rx_data;
            uart_ready <= 1'b1;
        end else if (in_oe && oar_addr == 8'h02) begin
            uart_ready <= 1'b0;
        end
    end
end

// Input ports multiplexer
reg [7:0] in_port_data;
wire [15:0] mouse_x;
wire [15:0] mouse_y;
wire [7:0]  mouse_btn;
always @(*) begin
    case (oar_addr)
        8'h00: in_port_data = kb_data;
        8'h01: in_port_data = {7'b0, kb_ready};
        8'h02: in_port_data = uart_data_in;
        8'h03: in_port_data = {6'b0, uart_ready, uart_tx_busy};
		8'h04: in_port_data = mouse_x[7:0];   // Mouse X Low Byte
		8'h05: in_port_data = mouse_x[15:8];  // Mouse X High Byte
		8'h06: in_port_data = mouse_y[7:0];   // Mouse Y Low Byte
		8'h07: in_port_data = mouse_y[15:8];  // Mouse Y High Byte
		8'h08: in_port_data = mouse_btn;      // Mouse Buttons
		8'h09: in_port_data = {7'b0, vga_vblank}; // VGA VBLANK Status
		8'h0A: in_port_data = sd_rx_data;     // SD Card SPI RX Data
		8'h0B: in_port_data = {7'b0, sd_spi_ready}; // SD Card SPI Status
        default: in_port_data = 8'h00;
    endcase
end

// Bus multiplexing logic: only one component drives the bus at a time
always @(*) begin
	bus = 16'b0;

	if (reg_oe)
		bus = reg_out;           // Register file drives bus
	else if (mem_oe)
		bus = {8'b0, mem_out};   // Memory drives bus
	else if (alu_oe)
		bus = {8'b0, alu_out};   // ALU drives bus
	else if (alu_flags_oe)
		bus = {8'b0, alu_flags}; // ALU flags drive bus
	else if (in_oe)
		bus = {8'b0, in_port_data}; // Input ports drive bus
end

// Output port latch for I/O operations
always @(posedge clk or posedge rst) begin
    if (rst) begin
        oar_addr <= 8'b0;
        port_out <= 72'b0;
        sd_cs_n <= 1'b1;
        sd_fast_mode <= 1'b0;
        sd_tx_latch <= 8'hFF;
    end else begin
        if (oar_we)
            oar_addr <= bus[7:0];

        if (out_we) begin
            case (oar_addr)
                8'd0: port_out[7:0] <= bus[7:0];
                8'd1: port_out[35:0] <= {28'b0, bus[7:0]};
                8'd2: port_out[71:36] <= {28'b0, bus[7:0]};
                8'h0A: sd_tx_latch <= bus[7:0]; // Safe CPU-clock domain latch
                8'h0B: {sd_fast_mode, sd_cs_n} <= bus[1:0]; // SPI Control Reg
                default: ;
            endcase
        end
    end
end

// ========================================================
// USB 12MHz Clock Generation Workaround
// ========================================================
wire clk_24mhz;
usb_vga_pll usb_vga_pll_inst (
	.inclk0(CLOCK_21),
	.c0(clk_21mhz), // Phase-aligned 21.477 MHz
	.c1(clk_24mhz)
);


reg clk_12mhz = 0;
always @(posedge clk_24mhz) begin
	clk_12mhz <= ~clk_12mhz; // Perfect 50% duty cycle 12MHz
end

// Step button controller for manual clock stepping
step_button step_button(
	.clk(clk_sys),
	.rst(rst),
	.step_mode(step_mode),
	.step_clk_pulse(step_clk_pulse),
	.hlt_m(hlt_m)
);

// Clock generator with halt and step controls
clock clock(
	.hlt(hlt | hlt_m),
	.step_pulse(step_clk_pulse),
	.clk_in(clk_sys),
	.clk_out(clk)
);

// Register file: contains all CPU registers (BC, DE, HL, WZ, PC, SP)
reg_file reg_file(
	.clk(clk),
	.rst(rst),
	.rd_sel(reg_rd_sel),
	.wr_sel(reg_wr_sel),
	.ext(reg_ext),
	.we(reg_we),
	.data_in(bus),
	.data_out(reg_out)
);

// Memory subsystem: RAM and Memory Address Register
memory memory(
	.clk(clk),
	.rst(rst),
	.mar_we(mem_mar_we),
	.ram_we(mem_ram_we),
	.bus(bus),
	.out(mem_out),
	.vga_gfx_addr(vga_gfx_addr),
	.vga_gfx_data(vga_gfx_data),
	.vga_txt_addr(vga_txt_addr),
	.vga_txt_data(vga_txt_data),
	.vga_font_addr(vga_font_addr),
	.vga_font_data(vga_font_data),
	.ink_color(ink_color),
	.bg_color(bg_color),
	.cursor_x(cursor_x),
	.cursor_y(cursor_y),
	.cursor_style(cursor_style),
	.gfx_ink_color(gfx_ink_color)
);

// ========================================================
// Audio Synthesizer Integration
// ========================================================

// Memory Address Latch for address decoding outside of memory.v
reg [15:0] mar;
always @(posedge clk or posedge rst) begin
    if (rst) begin
        mar <= 16'b0;
    end else if (mem_mar_we) begin
        mar <= bus;
    end
end

// Audio Synthesizer Control Registers
reg [15:0] synth_pitch;
reg [7:0]  synth_volume;
reg        synth_gate;
reg        synth_seq_en;

always @(posedge clk or posedge rst) begin
    if (rst) begin
        synth_pitch <= 16'd0;
        synth_volume <= 8'd0;
        synth_gate <= 1'b0;
        synth_seq_en <= 1'b0;
    end else if (mem_ram_we && mar[15:4] == 12'hC01) begin // 0xC010 to 0xC01F
        case (mar[3:0])
            4'h0: synth_pitch[7:0] <= bus[7:0];
            4'h1: synth_pitch[15:8] <= bus[7:0];
            4'h2: synth_volume <= bus[7:0];
            4'h3: synth_gate <= bus[0];
            4'h4: synth_seq_en <= bus[0];
            default: ;
        endcase
    end
end

wire synth_ram_we = mem_ram_we && (mar[15:10] == 6'h18); // 0x6000 - 0x63FF
wire seq_ram_we   = mem_ram_we && (mar[15:8] == 8'h64);  // 0x6400 - 0x64FF

wire [5:0] audio_out_sig;
sap3_audio_synth audio_synth (
    .clk(clk_sys), // Use continuous system clock for audio
    .rst(rst),
    .pitch_step(synth_pitch),
    .volume(synth_volume),
    .gate_en(synth_gate),
    .seq_en(synth_seq_en),
    .seq_addr(mar[7:0]),
    .seq_data_in(bus[7:0]),
    .seq_we(seq_ram_we),
    .cpu_addr(mar[9:0]),
    .cpu_data_in(bus[7:0]),
    .cpu_we(synth_ram_we),
    .audio_out(audio_out_sig)
);

assign AUDIO_L = audio_out_sig;
assign AUDIO_R = audio_out_sig;

// Instruction Register: holds current instruction opcode
ir ir(
	.clk(clk),
	.rst(rst),
	.we(ir_we),
	.bus(bus[7:0]),
	.out(ir_out)
);

alu alu(
	.clk(clk),
	.rst(rst),
	.cs(alu_cs),
	.flags_we(alu_flags_we),
	.a_we(alu_a_we),
	.a_store(alu_a_store),
	.a_restore(alu_a_restore),
	.tmp_we(alu_tmp_we),
	.op(alu_op),
	.bus(bus[7:0]),
	.flags(alu_flags),
	.out(alu_out)
);

// Controller: generates control signals based on instruction opcode
controller controller(
	.clk(clk),
	.rst(rst),
	.opcode(ir_out),
	.flags(alu_flags),
	.out({
		in_oe,
		oar_we,
		out_we,
		hlt,
		alu_cs,
		alu_flags_we,
		alu_a_we,
		alu_a_store,
		alu_a_restore,
		alu_tmp_we,
		alu_op,
		alu_oe,
		alu_flags_oe,
		reg_rd_sel,
		reg_wr_sel,
		reg_ext,
		reg_oe,
		reg_we,
		mem_ram_we,
		mem_mar_we,
		mem_oe,
		ir_we
		})
);

// PS/2 Keyboard Interface
ps2_keyboard ps2_keyboard_inst(
	.clk(clk_sys),
	.rst(~RESET_N), // IMPORTANT: Use only physical reset to prevent F5 suicide glitch
	.ps2_clk(PS2_CLK),
	.ps2_dat(PS2_DAT),
	.scan_code(ps2_scan_code),
	.scan_code_ready(ps2_scan_code_ready),
	.sys_reset(kb_sys_reset)
);

// UART Interface
uart #(
	.CLOCKS_PER_BIT(186) // 21.477MHz / 115200 baud
) uart_inst (
	.clk(clk_sys),
	.rst(rst),
	.rx(UART_RXD),
	.tx(UART_TXD),
	.tx_data(bus[7:0]),              // Transmit data from CPU bus
	.tx_we(out_we && oar_addr == 8'h02), // Trigger transmission on OUT 0x02
	.tx_busy(uart_tx_busy),
	.rx_data(uart_rx_data),
	.rx_done(uart_rx_done)
);

// VGA Display Controller
display_controller vga_ctrl(
	.clk(clk_sys),
	.rst(rst),
	.vga_gfx_addr(vga_gfx_addr),
	.vga_gfx_data(vga_gfx_data),
	.vga_txt_addr(vga_txt_addr),
	.vga_txt_data(vga_txt_data),
	.vga_font_addr(vga_font_addr),
	.vga_font_data(vga_font_data),
	.layer_enable(2'b11), // Both layers enabled by default
	.ink_color(ink_color),
	.bg_color(bg_color),
	.cursor_x(cursor_x),
	.cursor_y(cursor_y),
	.cursor_style(cursor_style),
	.gfx_ink_color(gfx_ink_color),
	.vblank(vga_vblank),
	.vga_hsync(VGA_HSYNC),
	.vga_vsync(VGA_VSYNC),
	.vga_r(VGA_R),
	.vga_g(VGA_G),
	.vga_b(VGA_B)
);

// USB Mouse Integration
sap3_mouse_wrapper mouse_ctrl (
	.clk(clk_sys), // Use free-running clock for CDC synchronizer, not gated CPU clock
	.usbclk(clk_12mhz),
	.rst(rst),
	.usb_dp(USBP2),
	.usb_dm(USBN2),
	.mouse_x(mouse_x),
	.mouse_y(mouse_y),
	.mouse_btn(mouse_btn)
);

// SD Card SPI Master
assign SD_DAT3 = sd_cs_n; // Drive SD_DAT3 pin as Chip Select (Active Low)
assign SD_DAT1 = 1'b1;    // Prevent floating/grounding
assign SD_DAT2 = 1'b1;    // Prevent floating/grounding

sd_spi_master sd_spi (
    .clk(clk_sys),
    .rst(rst),
    .tx_data(sd_tx_latch),
    .tx_start(sd_tx_start),
    .fast_mode(sd_fast_mode),
    .rx_data(sd_rx_data),
    .ready(sd_spi_ready),
    .spi_clk(SD_CLK),
    .spi_mosi(SD_CMD),
    .spi_miso(SD_DAT0)
);

endmodule
